---
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
#before_install: 
#  - openssl aes-256-cbc -K $encrypted_25c51ccabb0e_key -iv $encrypted_25c51ccabb0e_iv -in travis_test_env.tar.enc -out travis_test_env.tar -d
#  - tar xvf travis_test_env.tar
install: 
  - pip install -r requirements-dev.txt
  - pip install tox-travis
script: 
  - pylama .
  - tox
